export const FETCH_USER = 'FETCH_USER';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const CREATE_EVENT = 'CREATE_EVENT';

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'