export const FETCH_USER = 'FETCH_USER';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const FETCH_ATTENDANCE = 'FETCH_ATTENDANCE';

export const CREATE_EVENT = 'CREATE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';

export const CREATE_PLAYER = 'CREATE_PLAYER';
export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const DELETE_PLAYER = 'DELETE_PLAYER';

export const FETCH_NEXT_EVENT = 'FETCH_NEXT_EVENT';

export const DELETE_EVENT = 'DELETE_EVENT';

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'